#!/usr/bin/python2
from subprocess import call
from os import system
import sys

for line in sys.stdin.readlines():
    stones = line.split()
    cmd = ('./kalah-s -t 20 -e 18 -d 13 -g p ' +
        ' '.join(stones[:6]) + ' 0 ' +
        ' '.join(stones[6:]) + ' 0 | ' +
        r'''sed -e 's/Move.\+m \([0-9]\).\+$/\1/' | \
        grep -v [a-z] | \
        head -n -1 ''')
    system(cmd)

