# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog.ui'
#
# Created: Fri Jul 26 03:12:59 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_kalah_options(object):
    def setupUi(self, kalah_options):
        kalah_options.setObjectName(_fromUtf8("kalah_options"))
        kalah_options.resize(238, 362)
        kalah_options.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(kalah_options)
        self.buttonBox.setGeometry(QtCore.QRect(-140, 320, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gameplay_box = QtGui.QGroupBox(kalah_options)
        self.gameplay_box.setGeometry(QtCore.QRect(10, 10, 221, 151))
        self.gameplay_box.setObjectName(_fromUtf8("gameplay_box"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gameplay_box)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.gameplay_box)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.ai_level_2 = QtGui.QSlider(self.gameplay_box)
        self.ai_level_2.setMinimum(1)
        self.ai_level_2.setMaximum(5)
        self.ai_level_2.setPageStep(1)
        self.ai_level_2.setProperty("value", 3)
        self.ai_level_2.setOrientation(QtCore.Qt.Horizontal)
        self.ai_level_2.setObjectName(_fromUtf8("ai_level_2"))
        self.gridLayout_3.addWidget(self.ai_level_2, 4, 2, 1, 1)
        self.player_1 = QtGui.QComboBox(self.gameplay_box)
        self.player_1.setObjectName(_fromUtf8("player_1"))
        self.gridLayout_3.addWidget(self.player_1, 1, 2, 1, 1)
        self.ai_level_1 = QtGui.QSlider(self.gameplay_box)
        self.ai_level_1.setMinimum(1)
        self.ai_level_1.setMaximum(5)
        self.ai_level_1.setPageStep(1)
        self.ai_level_1.setProperty("value", 3)
        self.ai_level_1.setOrientation(QtCore.Qt.Horizontal)
        self.ai_level_1.setObjectName(_fromUtf8("ai_level_1"))
        self.gridLayout_3.addWidget(self.ai_level_1, 2, 2, 1, 1)
        self.ai_level_label_2 = QtGui.QLabel(self.gameplay_box)
        self.ai_level_label_2.setObjectName(_fromUtf8("ai_level_label_2"))
        self.gridLayout_3.addWidget(self.ai_level_label_2, 4, 0, 1, 1)
        self.player_2 = QtGui.QComboBox(self.gameplay_box)
        self.player_2.setObjectName(_fromUtf8("player_2"))
        self.gridLayout_3.addWidget(self.player_2, 3, 2, 1, 1)
        self.ai_level_label_1 = QtGui.QLabel(self.gameplay_box)
        self.ai_level_label_1.setObjectName(_fromUtf8("ai_level_label_1"))
        self.gridLayout_3.addWidget(self.ai_level_label_1, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gameplay_box)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.gameplay_box)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.stones = QtGui.QSpinBox(self.gameplay_box)
        self.stones.setMinimumSize(QtCore.QSize(50, 0))
        self.stones.setMaximumSize(QtCore.QSize(50, 16777215))
        self.stones.setMinimum(3)
        self.stones.setMaximum(6)
        self.stones.setProperty("value", 3)
        self.stones.setObjectName(_fromUtf8("stones"))
        self.gridLayout_3.addWidget(self.stones, 0, 2, 1, 1)
        self.timing_box = QtGui.QGroupBox(kalah_options)
        self.timing_box.setGeometry(QtCore.QRect(10, 170, 221, 79))
        self.timing_box.setObjectName(_fromUtf8("timing_box"))
        self.gridLayout_2 = QtGui.QGridLayout(self.timing_box)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timer_on = QtGui.QCheckBox(self.timing_box)
        self.timer_on.setObjectName(_fromUtf8("timer_on"))
        self.gridLayout_2.addWidget(self.timer_on, 0, 0, 1, 1)
        self.time_per_move_label = QtGui.QLabel(self.timing_box)
        self.time_per_move_label.setObjectName(_fromUtf8("time_per_move_label"))
        self.gridLayout_2.addWidget(self.time_per_move_label, 1, 0, 1, 1)
        self.time_per_move = QtGui.QSpinBox(self.timing_box)
        self.time_per_move.setMinimumSize(QtCore.QSize(50, 0))
        self.time_per_move.setObjectName(_fromUtf8("time_per_move"))
        self.gridLayout_2.addWidget(self.time_per_move, 1, 1, 1, 1)
        self.visualization_box = QtGui.QGroupBox(kalah_options)
        self.visualization_box.setGeometry(QtCore.QRect(10, 260, 221, 53))
        self.visualization_box.setObjectName(_fromUtf8("visualization_box"))
        self.gridLayout = QtGui.QGridLayout(self.visualization_box)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.show_moves = QtGui.QCheckBox(self.visualization_box)
        self.show_moves.setObjectName(_fromUtf8("show_moves"))
        self.gridLayout.addWidget(self.show_moves, 0, 0, 1, 1)

        self.retranslateUi(kalah_options)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), kalah_options.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), kalah_options.reject)
        QtCore.QMetaObject.connectSlotsByName(kalah_options)

    def retranslateUi(self, kalah_options):
        kalah_options.setWindowTitle(QtGui.QApplication.translate("kalah_options", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.gameplay_box.setTitle(QtGui.QApplication.translate("kalah_options", "Gameplay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("kalah_options", "Stones:", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_level_label_2.setText(QtGui.QApplication.translate("kalah_options", "AI level:", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_level_label_1.setText(QtGui.QApplication.translate("kalah_options", "AI level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("kalah_options", "Player 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("kalah_options", "Player 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.timing_box.setTitle(QtGui.QApplication.translate("kalah_options", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.timer_on.setText(QtGui.QApplication.translate("kalah_options", "Timer ON", None, QtGui.QApplication.UnicodeUTF8))
        self.time_per_move_label.setText(QtGui.QApplication.translate("kalah_options", "Timer per move, sec:", None, QtGui.QApplication.UnicodeUTF8))
        self.visualization_box.setTitle(QtGui.QApplication.translate("kalah_options", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.show_moves.setText(QtGui.QApplication.translate("kalah_options", "Show moves", None, QtGui.QApplication.UnicodeUTF8))

