#!/bin/bash
export oldfile=$(ls | grep -E -e "^Version..\.py$" | tail -n1)
export oldver=$(echo $oldfile | sed -e 's/Version\(.\+\)\.py$/\1/' )
echo $oldver
newver=$(echo "1 + $oldver" | bc)
newfile="Version${newver}.py"
cp $oldfile $newfile -i

sed -i "s/Version$oldver/Version$newver/g" $newfile
chmod +x $newfile
$EDITOR $newfile

